### ISSUE TITLE
Epic: Bundled Observability

### ISSUE THREAD

**Issue by dannykopping** [coder/observability#1]
This is the holding issue for the set of improvements we want to make based on [RFC: Bundled Observability](https://github.com/coder/coder/discussions/12793).

**Goal**: produce a separate Helm chart which can be installed with one script to observe a Coder deployment. Each sub-chart should contain at least one dashboard, alert, and runbook to cover its own functional requirements (i.e. the Grafana installation should have a dashboard, alert, runbook to enable operators to observe it). The Coder deployment should be covered by several dashboards, alerts & runbooks, and we should collect all telemetry signals as applicable (metrics, logs, traces, profiles).

**Initial Requirements**:

- [x] Deploy the LGTM stack in our internal environment to setup & configure (https://github.com/coder/dogfood/issues/43)
- [x] Create a new Helm chart for bundled observability
  - [x] coder/coder#12798
  - [x] coder/coder#12799
    - [ ] Enable configureable notification routes _(maybe offer Coder deployment as notification target, display alerts in UI?)_
  - [x] coder/coder#12800
    - [ ] Enable configureable notification routes _(maybe offer Coder deployment as notification target, display alerts in UI?)_
  - [x] coder/coder#12994
  - [x] coder/coder#12995
  - [x] coder/coder#12996
  - [x] coder/coder#12997
- [ ] Create observability resources
  - [ ] #2
  - [ ] #3
  - [x] Pull in dashboard(s) for Postgres
  - [ ] #4
  - [x] #5
    - [ ] Include optional but recommended note about installing this chart in the [k8s docs](https://coder.com/docs/v2/latest/install/kubernetes)
  - [ ] #6

**Eventual Requirements**:
- [ ] Add & configure profiling chart, add Grafana datasource
- [ ] Add & configure tracing chart, add Grafana datasource
