### ISSUE TITLE
Support non-k8s workspaces

### ISSUE THREAD

**Issue by dannykopping** [coder/observability#9]
Currently we only scrape telemetry data from Kubernetes-deployed workspaces. Workspaces deployed currently via Docker, AWS, etc will not be discovered and therefore not covered by dashboards or alerts.

Using Grafana Agent on the client (i.e. where the workspaces are deployed), we can scrape workspaces' telemetry from non-k8s targets (e.g. Docker) by:

- discovering all containers ([`discovery.docker`](https://grafana.com/docs/agent/latest/flow/reference/components/discovery.docker/))
- scraping their metrics ([`prometheus.scrape`](https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.scrape/)), and forwarding them to the Grafana Agent deployed by the helm chart ([`prometheus.receive_http`](https://grafana.com/docs/agent/latest/flow/reference/components/prometheus.receive_http/))
- scraping their logs ([`loki.source.docker`](https://grafana.com/docs/agent/latest/flow/reference/components/loki.source.docker)), and forwarding them to the Grafana Agent deployed by the helm chart ([`loki.source.api`](https://grafana.com/docs/agent/latest/flow/reference/components/loki.source.api/))

## Tasks
- [ ] Validate technical implementation
- [ ] Document solution for Docker
- [ ] Document solution for AWS
- [ ] Document solution for GCP
- [ ] Document solution for Azure
- [ ] Document solution for OpenStack
